engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
  - "**.html"